W5D1/MusicApp_rspec/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :create]

  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:index, :new]
end

W5D1/MusicApp_rspec/app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :bigint(8)        not null, primary key
#  album_id    :integer          not null
#  title       :string           not null
#  ord         :integer          not null
#  lyrics      :text
#  bonus_track :boolean          default(FALSE), not null
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Track < ApplicationRecord
  validates :title, :ord, presence: true
  validates :bonus_track, inclusion: {in: [true,false]}

  belongs_to :album

end

W5D1/MusicApp_rspec/app/controllers/tracks_controller.rb
class TracksController < ApplicationController

  before_action :require_login

  def show
    @track = Track.find_by(id: params[:id])

    if @track
      render :show
    else
      redirect_to album_url(params[:track][:album_id])
    end
  end

  def new
    @track = Track.new
    render :new
  end
  def create
    @track = Track.new(track_params)

    if @track.save
      redirect_to track_url(@track)
    else
      flash[:errors] = @track.errors.full_messages
      redirect_to album_url(params[:track][:album_id])
    end
  end

  def edit
    @track = Track.find_by(id: params[:id])

    if @track
      render :edit
    else
      redirect_to album_url(params[:track][:album_id])
    end
  end
  def update
    @track = Track.find_by(id: params[:id])

    if @track.update(track_params)
      redirect_to album_url(params[:track][:album_id])
    else
      flash.now[:errors] = @track.errors.full_messages
      render :edit
    end
  end

  def destroy
    @track = Track.find_by(id: params[:id])
    @track.destroy
    redirect_to bands_url
  end

  private

  def track_params
    params.require(:track).permit(:title, :ord, :album_id, :bonus_track, :lyrics)
  end
end

W5D1/MusicApp_rspec/app/helpers/tracks_helper.rb
module TracksHelper
end

W5D1/MusicApp_rspec/app/views/tracks/_form.html.erb
<% if type == :new %>
  <% action_url = tracks_url %>
  <% method = :post %>
  <% button = "Create" %>
<% else %>
  <% action_url = track_url(track) %>
  <% method = :patch %>
  <% button = "Edit" %>
<% end %>

<ul>
  <%= button %> Track:
</ul>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if method == :patch %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label>Track Title:
    <input type="text" name="track[title]" value="<%= track.title %>">
  </label>
  <label>Track ord:
    <input type="text" name="track[ord]" value="<%= track.ord %>">
  </label>
  <label>Track Album:

    <select name="track[album_id]">
      <option disabled selected value="">-- Make a Selection --</option>
      <% Album.all.each do |album| %>
      <option <%="selected" if album.id == track.album_id  %> value="<%= album.id %>"> <%= album.title %> </option>
      <% end %>
    </select>

  </label>
  <label>Track type:

    <label>Regular
      <input <%="checked" if !track.bonus_track %> type="radio" name="track[bonus_track]" value="<%= false %>">
    </label>

    <label>Bonus
      <input <%="checked" if track.bonus_track %> type="radio" name="track[bonus_track]" value="<%= true %>">
    </label>

  </label>


  <input type="submit" value="<%= button %> track">

</form>

W5D1/MusicApp_rspec/app/views/tracks/_track.html.erb
<ul>
  <li>Track Title: <%= link_to track.title, track_url(track)%> </li>
  <li>Track ord: <%= track.ord %>  </li>
  <li>Bonus Track?: <%= track.bonus_track %>  </li>
  <li>Lyrics: <%= track.lyrics %> </li>
  <li> <%= link_to "Edit Track", edit_track_url(track) %>  </li>
  <li> <%= button_to "Delete Track", track_url(track), method: :delete %>  </li>
</ul>

W5D1/MusicApp_rspec/app/views/tracks/edit.html.erb
<%= render 'form', track: @track, type: :edit %>

W5D1/MusicApp_rspec/app/views/tracks/new.html.erb
<%= render 'form', track: @track, type: :new %>

W5D1/MusicApp_rspec/app/views/tracks/show.html.erb
<%= render 'track', track: @track %>