W5D1/MusicApp_rspec/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :session, only: [:new, :create, :destroy]
  resources :users, only: [:new, :show, :create]

  resources :bands do
    resources :albums, only: [:new]
  end
  resources :albums, except: [:index, :new] do
    resources :tracks, only: [:new]
  end
  resources :tracks, except: [:index, :new]
end

W5D1/MusicApp_rspec/app/models/album.rb
# == Schema Information
#
# Table name: albums
#
#  id         :bigint(8)        not null, primary key
#  title      :string           not null
#  year       :integer          not null
#  band_id    :integer          not null
#  live_album :boolean          default(FALSE), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Album < ApplicationRecord
  validates :title, :year, presence: true
  validates :live_album, inclusion: {in: [true,false]}

  belongs_to :band

  has_many :tracks, dependent: :destroy

end

W5D1/MusicApp_rspec/app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  before_action :require_login

  def show
    @album = Album.find_by(id: params[:id])

    if @album
      render :show
    else
      debugger
      redirect_to band_url(params[:album][:band_id])
    end
  end

  def new
    @album = Album.new
    render :new
  end
  def create
    @album = Album.new(album_params)

    if @album.save
      redirect_to album_url(@album)
    else
      flash[:errors] = @album.errors.full_messages
      redirect_to band_url(params[:album][:band_id])
    end
  end

  def edit
    @album = Album.find_by(id: params[:id])

    if @album
      render :edit
    else
      redirect_to band_url(params[:album][:band_id])
    end
  end
  def update
    @album = Album.find_by(id: params[:id])

    if @album.update(album_params)
      redirect_to band_url(params[:album][:band_id])
    else
      flash.now[:errors] = @album.errors.full_messages
      render :edit
    end
  end

  def destroy
    @album = Album.find_by(id: params[:id])
    @album.destroy
    redirect_to bands_url
  end

  private

  def album_params
    params.require(:album).permit(:title, :year, :band_id, :live_album)
  end
end

W5D1/MusicApp_rspec/app/helpers/albums_helper.rb
module AlbumsHelper
end

W5D1/MusicApp_rspec/app/views/albums/_album.html.erb
<ul>
  <li>Album Title: <%= link_to album.title, album_url(album)%> </li>
  <li>Album Year: <%= album.year %>  </li>
  <li>Live Album?: <%= album.live_album %>  </li>
  <li> <%= link_to "Edit Album", edit_album_url(album) %>  </li>
  <li> <%= button_to "Delete Album", album_url(album), method: :delete %>  </li>
</ul>

W5D1/MusicApp_rspec/app/views/albums/_form.html.erb
<% if type == :new %>
  <% action_url = albums_url %>
  <% method = :post %>
  <% button = "Create" %>
<% else %>
  <% action_url = album_url(album) %>
  <% method = :patch %>
  <% button = "Edit" %>
<% end %>

<ul>
  <%= button %> Album:
</ul>

<form action="<%= action_url %>" method="post">
  <%= auth_token %>
  <% if method == :patch %>
    <input type="hidden" name="_method" value="patch">
  <% end %>

  <label>Album Title:
    <input type="text" name="album[title]" value="<%= album.title %>">
  </label>
  <label>Album Year:
    <input type="text" name="album[year]" value="<%= album.year %>">
  </label>
  <label>Album Band:

    <select name="album[band_id]">
      <option disabled selected value="">-- Make a Selection --</option>
      <% Band.all.each do |band| %>
      <option <%="selected" if band.id == album.band_id  %> value="<%= band.id %>"> <%= band.name %> </option>
      <% end %>
    </select>

  </label>
  <label>Album type:

    <label>Studio
      <input <%="checked" if !album.live_album %> type="radio" name="album[live_album]" value="<%= false %>">
    </label>

    <label>Live
      <input <%="checked" if album.live_album %> type="radio" name="album[live_album]" value="<%= true %>">
    </label>

  </label>


  <input type="submit" value="<%= button %> album">

</form>

W5D1/MusicApp_rspec/app/views/albums/edit.html.erb
<%= render 'form', album: @album, type: :edit %>

W5D1/MusicApp_rspec/app/views/albums/new.html.erb
<%= render 'form', album: @album, type: :new %>

W5D1/MusicApp_rspec/app/views/albums/show.html.erb
<%= render 'album', album: @album %>